query{
  categories(treeLevel:3){
    id,
    name,
    href,
    metaTagDescription,
    children{
      id,
      name,
      href,
      metaTagDescription,
      children{
        id,
        name,
        href,
        metaTagDescription,
        children{
          id,
          name,
          href,
          metaTagDescription
        }
      }
    }
  }
}

